### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by gdoddsy** [nirnachmani/Pixie-Plus-for-Home-Assistant#15]
I was able to retrieve the Application ID, ClientKey and InstallationID, but when I try to login now I get the below error.
The credentials work fine when I call the login via Postman. Any suggestions on what else I'm missing?

```

This error originated from a custom integration.

Logger: custom_components.Pixie-Plus-for-Home-Assistant-main.config_flow
Source: custom_components/Pixie-Plus-for-Home-Assistant-main/config_flow.py:78
integration: Pixie-Plus-for-Home-Assistant-main
First occurred: 10:00:59 PM (1 occurrences)
Last logged: 10:00:59 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/config_flow.py", line 78, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/config_flow.py", line 45, in validate_input
    await hass.async_add_executor_job(pixiepluslogin.login, data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: login() missing 1 required positional argument: 'data'
```

**Comment by nirnachmani** [comment]
Download the files again - this issue was raised and was fixed 30 minutes ago, something I didn't notice after recently updating the code.

**Comment by gdoddsy** [comment]
New version is getting this error:


```
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 10:19:46 PM (2 occurrences)
Last logged: 10:20:28 PM

Error setting up entry Pixie Plus for pixie_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/__init__.py", line 76, in async_setup_entry
    (devices_list, session_data) = await pixiepluslogin.pixie_login(hass, config)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/pixiepluslogin.py", line 53, in pixie_login
    devices_list = await getdevices(hass, config, session_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/pixiepluslogin.py", line 169, in getdevices
    return parse_devices(res, config, session_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Pixie-Plus-for-Home-Assistant-main/pixiepluslogin.py", line 177, in parse_devices
    numberofdevices = len(devices["results"][0]["deviceList"])
                          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'deviceList'
```

**Comment by nirnachmani** [comment]
It may be that the query doesn't return any devices. 
Can you change the logging level for Pixie Plus to debug? You do this by adding the following to configuration.yaml:

```
logger:
  logs:
    custom_components.pixie_plus: debug

```
There should be a log with "result of getdevices" and them some data. Which version of the pixie hub do you have?

**Comment by gdoddsy** [comment]
Just before the error, I get this:
```
Logger: py.warnings
Source: runner.py:189
First occurred: 11:01:53 PM (2 occurrences)
Last logged: 11:07:19 PM

/usr/local/lib/python3.12/asyncio/base_events.py:1991: RuntimeWarning: coroutine 'login' was never awaited handle = None # Needed to break cycles when an exception occurs.
```

**Comment by nirnachmani** [comment]
Did you restart HA for the logger to take effect? You will need to look at the detailed logs - they recently changed how it is done so it depends in what version of AH you have. It used to be a link at the bottom of the log, now you need to press on the 3 dots on the right top corner in the Logs page and press on "Show raw logs". you will need to scroll up as it won't show the older log entries, and then search of pixie.

**Comment by nirnachmani** [comment]
Also, just to make sure as you didn't answer my question above - do you have a pixie hub?

**Comment by gdoddsy** [comment]
I don't know what I've done differently, but I just tried it again to get the logs and it's working. I'll remove the extra logging.

Thanks for your assistance!
